using System;
using System.Collections.Generic;
using System.Reflection;

namespace ILRuntime.Runtime.Generated
{
    class CLRBindings
    {


        /// <summary>
        /// Initialize the CLR binding, please invoke this AFTER CLR Redirection registration
        /// </summary>
        public static void Initialize(ILRuntime.Runtime.Enviorment.AppDomain app)
        {
            System_NotImplementedException_Binding.Register(app);
            System_String_Binding.Register(app);
            System_Text_StringBuilder_Binding.Register(app);
            System_Object_Binding.Register(app);
            System_Collections_IEnumerable_Binding.Register(app);
            System_Collections_IEnumerator_Binding.Register(app);
            System_IDisposable_Binding.Register(app);
            System_Type_Binding.Register(app);
            Google_Protobuf_ByteString_Binding.Register(app);
            DCET_Model_ByteHelper_Binding.Register(app);
            System_Array_Binding.Register(app);
            System_Reflection_MemberInfo_Binding.Register(app);
            System_Reflection_PropertyInfo_Binding.Register(app);
            System_Reflection_MethodBase_Binding.Register(app);
            UnityEngine_Debug_Binding.Register(app);
            System_Exception_Binding.Register(app);
            System_Collections_IDictionary_Binding.Register(app);
            LitJson_JsonMapper_Binding.Register(app);
            DCET_Model_Log_Binding.Register(app);
            DCET_Model_IdGenerater_Binding.Register(app);
            UnityEngine_Object_Binding.Register(app);
            UnityEngine_GameObject_Binding.Register(app);
            UnityEngine_Transform_Binding.Register(app);
            System_Collections_Generic_Dictionary_2_Int64_ILTypeInstance_Binding.Register(app);
            System_Collections_Generic_Dictionary_2_Int64_ILTypeInstance_Binding_ValueCollection_Binding.Register(app);
            System_Collections_Generic_Dictionary_2_Int64_ILTypeInstance_Binding_ValueCollection_Binding_Enumerator_Binding.Register(app);
            System_Collections_Generic_Dictionary_2_Type_ILTypeInstance_Binding.Register(app);
            System_Collections_Generic_Dictionary_2_Type_ILTypeInstance_Binding_ValueCollection_Binding.Register(app);
            System_Collections_Generic_Dictionary_2_Type_ILTypeInstance_Binding_ValueCollection_Binding_Enumerator_Binding.Register(app);
            DCET_Model_Pool_1_Dictionary_2_Int64_ILTypeInstance_Binding.Register(app);
            DCET_Model_Pool_1_HashSet_1_ILTypeInstance_Binding.Register(app);
            System_Collections_Generic_HashSet_1_ILTypeInstance_Binding.Register(app);
            System_Collections_Generic_Dictionary_2_Type_ILTypeInstance_Binding_Enumerator_Binding.Register(app);
            System_Collections_Generic_KeyValuePair_2_Type_ILTypeInstance_Binding.Register(app);
            DCET_Model_Pool_1_Dictionary_2_Type_ILTypeInstance_Binding.Register(app);
            System_Collections_Generic_HashSet_1_ILTypeInstance_Binding_Enumerator_Binding.Register(app);
            System_Activator_Binding.Register(app);
            DCET_Model_LayerNames_Binding.Register(app);
            DCET_Model_ComponentView_Binding.Register(app);
            System_Collections_Generic_List_1_Object_Binding.Register(app);
            System_Collections_Generic_Dictionary_2_String_List_1_Object_Binding.Register(app);
            DCET_Model_UnOrderMultiMap_2_Type_ILTypeInstance_Binding.Register(app);
            System_Collections_Generic_Queue_1_Int64_Binding.Register(app);
            System_Collections_Generic_List_1_ILTypeInstance_Binding.Register(app);
            System_Collections_Generic_List_1_ILTypeInstance_Binding_Enumerator_Binding.Register(app);
            System_Collections_Generic_List_1_Object_Binding_Enumerator_Binding.Register(app);
            System_Collections_Generic_HashSet_1_Type_Binding.Register(app);
            System_Collections_Generic_Dictionary_2_Type_Int32_Binding.Register(app);
            System_Collections_Generic_Dictionary_2_Int64_ILTypeInstance_Binding_Enumerator_Binding.Register(app);
            System_Collections_Generic_KeyValuePair_2_Int64_ILTypeInstance_Binding.Register(app);
            System_Collections_Generic_HashSet_1_Type_Binding_Enumerator_Binding.Register(app);
            System_Linq_Enumerable_Binding.Register(app);
            System_Collections_Generic_IEnumerable_1_KeyValuePair_2_Type_Int32_Binding.Register(app);
            System_Collections_Generic_IEnumerator_1_KeyValuePair_2_Type_Int32_Binding.Register(app);
            System_Collections_Generic_KeyValuePair_2_Type_Int32_Binding.Register(app);
            System_Collections_Generic_List_1_Type_Binding.Register(app);
            DCET_Model_Game_Binding.Register(app);
            DCET_Model_Hotfix_Binding.Register(app);
            System_Collections_Generic_List_1_Type_Binding_Enumerator_Binding.Register(app);
            DCET_Model_EventAttribute_Binding.Register(app);
            DCET_Model_EventProxy_Binding.Register(app);
            DCET_Model_EventSystem_Binding.Register(app);
            System_Collections_Generic_Queue_1_ILTypeInstance_Binding.Register(app);
            DCET_Model_MultiMapSet_2_String_String_Binding.Register(app);
            System_Collections_Generic_SortedDictionary_2_String_HashSet_1_String_Binding.Register(app);
            System_Collections_Generic_SortedDictionary_2_String_HashSet_1_String_Binding_Enumerator_Binding.Register(app);
            System_Collections_Generic_KeyValuePair_2_String_HashSet_1_String_Binding.Register(app);
            System_Collections_Generic_HashSet_1_String_Binding.Register(app);
            System_Collections_Generic_HashSet_1_String_Binding_Enumerator_Binding.Register(app);
            System_Collections_Generic_Queue_1_ILTypeInstance_Binding_Enumerator_Binding.Register(app);
            System_Reflection_FieldInfo_Binding.Register(app);
            System_Reflection_CustomAttributeExtensions_Binding.Register(app);
            System_Math_Binding.Register(app);
            System_Collections_ICollection_Binding.Register(app);
            DCET_Model_ConfigAttribute_Binding.Register(app);
            DCET_Model_AppTypeHelper_Binding.Register(app);
            DCET_Model_Entity_Binding.Register(app);
            DCET_Model_ResourcesComponent_Binding.Register(app);
            DCET_Model_GameObjectHelper_Binding.Register(app);
            UnityEngine_TextAsset_Binding.Register(app);
            Google_Protobuf_ProtoPreconditions_Binding.Register(app);
            Google_Protobuf_CodedOutputStream_Binding.Register(app);
            Google_Protobuf_CodedInputStream_Binding.Register(app);
            Google_Protobuf_MessageParser_1_Google_Protobuf_Adapt_IMessage_Binding_Adaptor_Binding.Register(app);
            Google_Protobuf_Collections_RepeatedField_1_Google_Protobuf_Adapt_IMessage_Binding_Adaptor_Binding.Register(app);
            Google_Protobuf_Collections_RepeatedField_1_String_Binding.Register(app);
            Google_Protobuf_Collections_RepeatedField_1_Int32_Binding.Register(app);
            Google_Protobuf_Collections_RepeatedField_1_Int64_Binding.Register(app);
            Google_Protobuf_FieldCodec_Binding.Register(app);
            System_Collections_Generic_Dictionary_2_UInt16_List_1_ILTypeInstance_Binding.Register(app);
            DCET_Model_OpcodeTypeComponent_Binding.Register(app);
            DCET_Model_MessageProxy_Binding.Register(app);
            DCET_Model_MessageDispatcherComponent_Binding.Register(app);
            DCET_Model_MessageInfo_Binding.Register(app);
            System_Collections_Generic_Dictionary_2_Type_Queue_1_Object_Binding.Register(app);
            System_Collections_Generic_Queue_1_Object_Binding.Register(app);
            DCET_Model_DoubleMap_2_UInt16_Type_Binding.Register(app);
            System_Collections_Generic_Dictionary_2_UInt16_Object_Binding.Register(app);
            DCET_Model_MessageAttribute_Binding.Register(app);
            DCET_Model_SessionCallbackComponent_Binding.Register(app);
            System_Collections_Generic_Dictionary_2_Int32_Action_1_Google_Protobuf_Adapt_IMessage_Binding_Adaptor_Binding.Register(app);
            DCET_Model_Session_Binding.Register(app);
            System_Action_1_Google_Protobuf_Adapt_IMessage_Binding_Adaptor_Binding.Register(app);
            DCET_Model_NetworkComponent_Binding.Register(app);
            DCET_Model_IMessagePacker_Binding.Register(app);
            DCET_Model_OpcodeHelper_Binding.Register(app);
            DCET_Model_StringHelper_Binding.Register(app);
            DCET_Model_ETTaskCompletionSource_1_Google_Protobuf_Adapt_IMessage_Binding_Adaptor_Binding.Register(app);
            System_Threading_CancellationToken_Binding.Register(app);
            DCET_Model_ErrorCode_Binding.Register(app);
            DCET_Model_RpcException_Binding.Register(app);
            BehaviorDesigner_Runtime_Behavior_Binding.Register(app);
            UnityEngine_Component_Binding.Register(app);
            BehaviorDesigner_Runtime_BehaviorTreeController_Binding.Register(app);
            BehaviorDesigner_Runtime_ExternalBehavior_Binding.Register(app);
            System_Collections_Generic_Dictionary_2_Type_Dictionary_2_String_ILTypeInstance_Binding.Register(app);
            System_Collections_Generic_Dictionary_2_String_ILTypeInstance_Binding.Register(app);
            System_Collections_Generic_Dictionary_2_Type_Dictionary_2_String_ILTypeInstance_Binding_ValueCollection_Binding.Register(app);
            System_Collections_Generic_Dictionary_2_Type_Dictionary_2_String_ILTypeInstance_Binding_ValueCollection_Binding_Enumerator_Binding.Register(app);
            System_Collections_Generic_Dictionary_2_String_ILTypeInstance_Binding_ValueCollection_Binding.Register(app);
            System_Collections_Generic_Dictionary_2_String_ILTypeInstance_Binding_ValueCollection_Binding_Enumerator_Binding.Register(app);
            FairyGUI_GObject_Binding.Register(app);
            FairyGUI_GComponent_Binding.Register(app);
            FairyGUI_GRoot_Binding.Register(app);
            System_Collections_Generic_Stack_1_ILTypeInstance_Binding.Register(app);
            DCET_Model_GWindow_Binding.Register(app);
            FairyGUI_Window_Binding.Register(app);
            UnityEngine_Rect_Binding.Register(app);
            UnityEngine_Mathf_Binding.Register(app);
            System_Collections_Generic_Dictionary_2_GObject_ILTypeInstance_Binding.Register(app);
            System_Collections_Generic_List_1_HotfixAction_Binding.Register(app);
            System_Collections_Generic_List_1_HotfixAction_Binding_Enumerator_Binding.Register(app);
            System_Collections_Generic_Dictionary_2_HotfixAction_ILTypeInstance_Binding.Register(app);
            System_Collections_Generic_List_1_HotfixComposite_Binding.Register(app);
            System_Collections_Generic_List_1_HotfixComposite_Binding_Enumerator_Binding.Register(app);
            System_Collections_Generic_Dictionary_2_HotfixComposite_ILTypeInstance_Binding.Register(app);
            System_Collections_Generic_List_1_HotfixConditional_Binding.Register(app);
            System_Collections_Generic_List_1_HotfixConditional_Binding_Enumerator_Binding.Register(app);
            System_Collections_Generic_Dictionary_2_HotfixConditional_ILTypeInstance_Binding.Register(app);
            System_Collections_Generic_List_1_HotfixDecorator_Binding.Register(app);
            System_Collections_Generic_List_1_HotfixDecorator_Binding_Enumerator_Binding.Register(app);
            System_Collections_Generic_Dictionary_2_HotfixDecorator_ILTypeInstance_Binding.Register(app);
            System_Collections_Generic_Dictionary_2_HotfixAction_ILTypeInstance_Binding_Enumerator_Binding.Register(app);
            System_Collections_Generic_KeyValuePair_2_HotfixAction_ILTypeInstance_Binding.Register(app);
            System_Collections_Generic_Dictionary_2_HotfixComposite_ILTypeInstance_Binding_Enumerator_Binding.Register(app);
            System_Collections_Generic_KeyValuePair_2_HotfixComposite_ILTypeInstance_Binding.Register(app);
            System_Collections_Generic_Dictionary_2_HotfixConditional_ILTypeInstance_Binding_Enumerator_Binding.Register(app);
            System_Collections_Generic_KeyValuePair_2_HotfixConditional_ILTypeInstance_Binding.Register(app);
            System_Collections_Generic_Dictionary_2_HotfixDecorator_ILTypeInstance_Binding_Enumerator_Binding.Register(app);
            System_Collections_Generic_KeyValuePair_2_HotfixDecorator_ILTypeInstance_Binding.Register(app);
            BehaviorDesigner_Runtime_Tasks_HotfixAction_Binding.Register(app);
            BehaviorDesigner_Runtime_Tasks_Task_Binding.Register(app);
            BehaviorDesigner_Runtime_Tasks_HotfixDecorator_Binding.Register(app);
            BehaviorDesigner_Runtime_Tasks_HotfixConditional_Binding.Register(app);
            BehaviorDesigner_Runtime_Tasks_HotfixComposite_Binding.Register(app);
            UnityEngine_LayerMask_Binding.Register(app);
            UnityEngine_Input_Binding.Register(app);
            UnityEngine_Camera_Binding.Register(app);
            UnityEngine_Physics_Binding.Register(app);
            UnityEngine_RaycastHit_Binding.Register(app);
            UnityEngine_Vector3_Binding.Register(app);
            DCET_Model_Frame_ClickMap_Binding.Register(app);
            DCET_Model_SessionComponent_Binding.Register(app);
            DCET_Model_ETVoid_Binding.Register(app);
            DCET_Model_AsyncETVoidMethodBuilder_Binding.Register(app);
            DCET_Model_ETTask_1_Google_Protobuf_Adapt_IMessage_Binding_Adaptor_Binding.Register(app);
            DCET_Model_ETTask_1_Google_Protobuf_Adapt_IMessage_Binding_Adaptor_Binding_Awaiter_Binding.Register(app);
            System_Runtime_CompilerServices_AsyncTaskMethodBuilder_Binding.Register(app);
            DCET_Model_FUIPackageComponent_Binding.Register(app);
            DCET_Model_ETTask_Binding.Register(app);
            DCET_Model_ETTask_Binding_Awaiter_Binding.Register(app);
            DCET_Model_AsyncETTaskMethodBuilder_Binding.Register(app);
            DCET_Model_M2C_CreateUnits_Binding.Register(app);
            Google_Protobuf_Collections_RepeatedField_1_UnitInfo_Binding.Register(app);
            System_Collections_Generic_IEnumerator_1_UnitInfo_Binding.Register(app);
            DCET_Model_UnitInfo_Binding.Register(app);
            DCET_Model_UnitComponent_Binding.Register(app);
            DCET_Model_UnitFactory_Binding.Register(app);
            DCET_Model_Unit_Binding.Register(app);
            DCET_Model_M2C_PathfindingResult_Binding.Register(app);
            DCET_Model_AnimatorComponent_Binding.Register(app);
            DCET_Model_UnitPathComponent_Binding.Register(app);
            DCET_Model_GizmosDebug_Binding.Register(app);
            System_Collections_Generic_List_1_Vector3_Binding.Register(app);
            Google_Protobuf_Collections_RepeatedField_1_Single_Binding.Register(app);
            DCET_Model_GlobalConfigComponent_Binding.Register(app);
            DCET_Model_GlobalProto_Binding.Register(app);
            DCET_Model_EntityFactory_Binding.Register(app);
            DCET_Model_PlayerComponent_Binding.Register(app);
            DCET_Model_SceneChangeComponent_Binding.Register(app);
            DCET_Model_C2G_EnterMap_Binding.Register(app);
            DCET_Model_ETTask_1_IResponse_Binding.Register(app);
            DCET_Model_ETTask_1_IResponse_Binding_Awaiter_Binding.Register(app);
            DCET_Model_G2C_EnterMap_Binding.Register(app);
            DCET_Model_Player_Binding.Register(app);
            System_Runtime_CompilerServices_AsyncVoidMethodBuilder_Binding.Register(app);
            System_Threading_Tasks_Task_Binding.Register(app);
            System_Runtime_CompilerServices_TaskAwaiter_Binding.Register(app);
            FairyGUI_UIPackage_Binding.Register(app);
            System_Threading_Tasks_TaskCompletionSource_1_ILTypeInstance_Binding.Register(app);
            System_Int64_Binding.Register(app);

            ILRuntime.CLR.TypeSystem.CLRType __clrType = null;
        }

        /// <summary>
        /// Release the CLR binding, please invoke this BEFORE ILRuntime Appdomain destroy
        /// </summary>
        public static void Shutdown(ILRuntime.Runtime.Enviorment.AppDomain app)
        {
        }
    }
}
