-- Generated by CSharp.lua Compiler
--[[ Copyright 2010-present MongoDB Inc.
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
]]
local System = System
local MongoDBBson
System.import(function (out)
  MongoDBBson = MongoDB.Bson
end)
System.namespace("MongoDB.Bson", function (namespace)
  -- <summary>
  -- Represents a BSON internal exception (almost surely the result of a bug).
  -- </summary>
  namespace.class("BsonInternalException", function (namespace)
    local __ctor1__, __ctor2__, __ctor3__, __ctor4__
    -- <summary>
    -- Initializes a new instance of the BsonInternalException class.
    -- </summary>
    __ctor1__ = function (this)
      MongoDBBson.BsonException.__ctor__[1](this)
    end
    -- <summary>
    -- Initializes a new instance of the BsonInternalException class.
    -- </summary>
    __ctor2__ = function (this, message)
      MongoDBBson.BsonException.__ctor__[2](this, message)
    end
    -- <summary>
    -- Initializes a new instance of the BsonInternalException class.
    -- </summary>
    -- <param name="innerException">The inner exception.</param>
    __ctor3__ = function (this, message, innerException)
      MongoDBBson.BsonException.__ctor__[3](this, message, innerException)
    end
    -- <summary>
    -- Initializes a new instance of the BsonInternalException class (this overload used by deserialization).
    -- </summary>
    -- <param name="context">The StreamingContext.</param>
    __ctor4__ = function (this, info, context)
      MongoDBBson.BsonException.__ctor__[5](this, info, context)
    end
    return {
      base = function (out, this)
        local base = out.MongoDB.Bson.BsonException
        this.__tostring = base.__tostring
        return {
          base
        }
      end,
      __ctor__ = {
        __ctor1__,
        __ctor2__,
        __ctor3__,
        __ctor4__
      },
      __metadata__ = function (out)
        return {
          class = { 0x6, System.SerializableAttribute() }
        }
      end
    }
  end)
end)
