//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class FairyGUI_ButtonModeWrap
{
	public static void Register(LuaState L)
	{
		L.BeginEnum(typeof(FairyGUI.ButtonMode));
		L.RegConstant("Common", FairyGUI.ButtonMode.Common);
		L.RegConstant("Check", FairyGUI.ButtonMode.Check);
		L.RegConstant("Radio", FairyGUI.ButtonMode.Radio);
		L.EndEnum();
		TypeTraits<FairyGUI.ButtonMode>.Check = CheckType;
		StackTraits<FairyGUI.ButtonMode>.Push = Push;
	}

	static void Push(IntPtr L, FairyGUI.ButtonMode arg)
	{
		ToLua.Push(L, arg);
	}

	static bool CheckType(IntPtr L, int pos)
	{
		return TypeChecker.CheckEnumType(typeof(FairyGUI.ButtonMode), L, pos);
	}
}

