//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class FairyGUI_ListLayoutTypeWrap
{
	public static void Register(LuaState L)
	{
		L.BeginEnum(typeof(FairyGUI.ListLayoutType));
		L.RegConstant("SingleColumn", FairyGUI.ListLayoutType.SingleColumn);
		L.RegConstant("SingleRow", FairyGUI.ListLayoutType.SingleRow);
		L.RegConstant("FlowHorizontal", FairyGUI.ListLayoutType.FlowHorizontal);
		L.RegConstant("FlowVertical", FairyGUI.ListLayoutType.FlowVertical);
		L.RegConstant("Pagination", FairyGUI.ListLayoutType.Pagination);
		L.EndEnum();
		TypeTraits<FairyGUI.ListLayoutType>.Check = CheckType;
		StackTraits<FairyGUI.ListLayoutType>.Push = Push;
	}

	static void Push(IntPtr L, FairyGUI.ListLayoutType arg)
	{
		ToLua.Push(L, arg);
	}

	static bool CheckType(IntPtr L, int pos)
	{
		return TypeChecker.CheckEnumType(typeof(FairyGUI.ListLayoutType), L, pos);
	}
}

