//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class Google_Protobuf_MessageParserWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(Google.Protobuf.MessageParser), typeof(System.Object));
		L.RegFunction("ParseFrom", ParseFrom);
		L.RegFunction("ParseDelimitedFrom", ParseDelimitedFrom);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ParseFrom(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 2 && TypeChecker.CheckTypes<byte[]>(L, 2))
			{
				Google.Protobuf.MessageParser obj = (Google.Protobuf.MessageParser)ToLua.CheckObject<Google.Protobuf.MessageParser>(L, 1);
				byte[] arg0 = ToLua.CheckByteBuffer(L, 2);
				Google.Protobuf.IMessage o = obj.ParseFrom(arg0);
				ToLua.PushObject(L, o);
				return 1;
			}
			else if (count == 2 && TypeChecker.CheckTypes<Google.Protobuf.ByteString>(L, 2))
			{
				Google.Protobuf.MessageParser obj = (Google.Protobuf.MessageParser)ToLua.CheckObject<Google.Protobuf.MessageParser>(L, 1);
				Google.Protobuf.ByteString arg0 = (Google.Protobuf.ByteString)ToLua.ToObject(L, 2);
				Google.Protobuf.IMessage o = obj.ParseFrom(arg0);
				ToLua.PushObject(L, o);
				return 1;
			}
			else if (count == 2 && TypeChecker.CheckTypes<System.IO.Stream>(L, 2))
			{
				Google.Protobuf.MessageParser obj = (Google.Protobuf.MessageParser)ToLua.CheckObject<Google.Protobuf.MessageParser>(L, 1);
				System.IO.Stream arg0 = (System.IO.Stream)ToLua.ToObject(L, 2);
				Google.Protobuf.IMessage o = obj.ParseFrom(arg0);
				ToLua.PushObject(L, o);
				return 1;
			}
			else if (count == 2 && TypeChecker.CheckTypes<Google.Protobuf.CodedInputStream>(L, 2))
			{
				Google.Protobuf.MessageParser obj = (Google.Protobuf.MessageParser)ToLua.CheckObject<Google.Protobuf.MessageParser>(L, 1);
				Google.Protobuf.CodedInputStream arg0 = (Google.Protobuf.CodedInputStream)ToLua.ToObject(L, 2);
				Google.Protobuf.IMessage o = obj.ParseFrom(arg0);
				ToLua.PushObject(L, o);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: Google.Protobuf.MessageParser.ParseFrom");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ParseDelimitedFrom(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Google.Protobuf.MessageParser obj = (Google.Protobuf.MessageParser)ToLua.CheckObject<Google.Protobuf.MessageParser>(L, 1);
			System.IO.Stream arg0 = (System.IO.Stream)ToLua.CheckObject<System.IO.Stream>(L, 2);
			Google.Protobuf.IMessage o = obj.ParseDelimitedFrom(arg0);
			ToLua.PushObject(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

