//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class Google_Protobuf_ProtoPreconditionsWrap
{
	public static void Register(LuaState L)
	{
		L.BeginStaticLibs("ProtoPreconditions");
		L.EndStaticLibs();
	}
}

