//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class Google_Protobuf_ByteStringWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(Google.Protobuf.ByteString), typeof(System.Object));
		L.RegFunction("ToByteArray", ToByteArray);
		L.RegFunction("ToBase64", ToBase64);
		L.RegFunction("FromBase64", FromBase64);
		L.RegFunction("FromStream", FromStream);
		L.RegFunction("CopyFrom", CopyFrom);
		L.RegFunction("CopyFromUtf8", CopyFromUtf8);
		L.RegFunction(".geti", get_Item);
		L.RegFunction("get", get_Item);
		L.RegFunction("get_Item", get_Item);
		L.RegFunction("get", get_Item);
		L.RegFunction("ToString", ToString);
		L.RegFunction("ToStringUtf8", ToStringUtf8);
		L.RegFunction("GetEnumerator", GetEnumerator);
		L.RegFunction("CreateCodedInput", CreateCodedInput);
		L.RegFunction("Equals", Equals);
		L.RegFunction("GetHashCode", GetHashCode);
		L.RegFunction("CopyTo", CopyTo);
		L.RegFunction("WriteTo", WriteTo);
		L.RegFunction("New", _CreateGoogle_Protobuf_ByteString);
		L.RegVar("this", _this, null);
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("bytes", get_bytes, set_bytes);
		L.RegVar("Empty", get_Empty, null);
		L.RegFunction("getEmpty", get_Empty);
		L.RegVar("Length", get_Length, null);
		L.RegFunction("getLength", get_Length);
		L.RegVar("IsEmpty", get_IsEmpty, null);
		L.RegFunction("getIsEmpty", get_IsEmpty);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateGoogle_Protobuf_ByteString(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				Google.Protobuf.ByteString obj = new Google.Protobuf.ByteString();
				ToLua.PushSealed(L, obj);
				return 1;
			}
			else if (count == 1 && TypeChecker.CheckTypes<System.Collections.Generic.List<byte>>(L, 1))
			{
				System.Collections.Generic.List<byte> arg0 = (System.Collections.Generic.List<byte>)ToLua.ToObject(L, 1);
				Google.Protobuf.ByteString obj = new Google.Protobuf.ByteString(arg0);
				ToLua.PushSealed(L, obj);
				return 1;
			}
			else if (count == 1 && TypeChecker.CheckTypes<byte[]>(L, 1))
			{
				byte[] arg0 = ToLua.CheckByteBuffer(L, 1);
				Google.Protobuf.ByteString obj = new Google.Protobuf.ByteString(arg0);
				ToLua.PushSealed(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: Google.Protobuf.ByteString.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _get_this(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Google.Protobuf.ByteString obj = (Google.Protobuf.ByteString)ToLua.CheckObject(L, 1, typeof(Google.Protobuf.ByteString));
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			byte o = obj[arg0];
			LuaDLL.lua_pushnumber(L, o);
			return 1;

		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _this(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushvalue(L, 1);
			LuaDLL.tolua_bindthis(L, _get_this, null);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ToByteArray(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Google.Protobuf.ByteString obj = (Google.Protobuf.ByteString)ToLua.CheckObject(L, 1, typeof(Google.Protobuf.ByteString));
			byte[] o = obj.ToByteArray();
			ToLua.Push(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ToBase64(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Google.Protobuf.ByteString obj = (Google.Protobuf.ByteString)ToLua.CheckObject(L, 1, typeof(Google.Protobuf.ByteString));
			string o = obj.ToBase64();
			LuaDLL.lua_pushstring(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int FromBase64(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			string arg0 = ToLua.CheckString(L, 1);
			Google.Protobuf.ByteString o = Google.Protobuf.ByteString.FromBase64(arg0);
			ToLua.PushSealed(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int FromStream(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			System.IO.Stream arg0 = (System.IO.Stream)ToLua.CheckObject<System.IO.Stream>(L, 1);
			Google.Protobuf.ByteString o = Google.Protobuf.ByteString.FromStream(arg0);
			ToLua.PushSealed(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int CopyFrom(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 2 && TypeChecker.CheckTypes<string, System.Text.Encoding>(L, 1))
			{
				string arg0 = ToLua.ToString(L, 1);
				System.Text.Encoding arg1 = (System.Text.Encoding)ToLua.ToObject(L, 2);
				Google.Protobuf.ByteString o = Google.Protobuf.ByteString.CopyFrom(arg0, arg1);
				ToLua.PushSealed(L, o);
				return 1;
			}
			else if (count == 3 && TypeChecker.CheckTypes<byte[], int, int>(L, 1))
			{
				byte[] arg0 = ToLua.CheckByteBuffer(L, 1);
				int arg1 = (int)LuaDLL.lua_tonumber(L, 2);
				int arg2 = (int)LuaDLL.lua_tonumber(L, 3);
				Google.Protobuf.ByteString o = Google.Protobuf.ByteString.CopyFrom(arg0, arg1, arg2);
				ToLua.PushSealed(L, o);
				return 1;
			}
			else if (TypeChecker.CheckParamsType<byte>(L, 1, count))
			{
				byte[] arg0 = ToLua.ToParamsNumber<byte>(L, 1, count);
				Google.Protobuf.ByteString o = Google.Protobuf.ByteString.CopyFrom(arg0);
				ToLua.PushSealed(L, o);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: Google.Protobuf.ByteString.CopyFrom");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int CopyFromUtf8(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			string arg0 = ToLua.CheckString(L, 1);
			Google.Protobuf.ByteString o = Google.Protobuf.ByteString.CopyFromUtf8(arg0);
			ToLua.PushSealed(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Item(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Google.Protobuf.ByteString obj = (Google.Protobuf.ByteString)ToLua.CheckObject(L, 1, typeof(Google.Protobuf.ByteString));
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			byte o = obj[arg0];
			LuaDLL.lua_pushnumber(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ToString(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 1)
			{
				Google.Protobuf.ByteString obj = (Google.Protobuf.ByteString)ToLua.CheckObject(L, 1, typeof(Google.Protobuf.ByteString));
				string o = obj.ToString();
				LuaDLL.lua_pushstring(L, o);
				return 1;
			}
			else if (count == 2)
			{
				Google.Protobuf.ByteString obj = (Google.Protobuf.ByteString)ToLua.CheckObject(L, 1, typeof(Google.Protobuf.ByteString));
				System.Text.Encoding arg0 = (System.Text.Encoding)ToLua.CheckObject<System.Text.Encoding>(L, 2);
				string o = obj.ToString(arg0);
				LuaDLL.lua_pushstring(L, o);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: Google.Protobuf.ByteString.ToString");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ToStringUtf8(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Google.Protobuf.ByteString obj = (Google.Protobuf.ByteString)ToLua.CheckObject(L, 1, typeof(Google.Protobuf.ByteString));
			string o = obj.ToStringUtf8();
			LuaDLL.lua_pushstring(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetEnumerator(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Google.Protobuf.ByteString obj = (Google.Protobuf.ByteString)ToLua.CheckObject(L, 1, typeof(Google.Protobuf.ByteString));
			System.Collections.Generic.IEnumerator<byte> o = obj.GetEnumerator();
			ToLua.PushObject(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int CreateCodedInput(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Google.Protobuf.ByteString obj = (Google.Protobuf.ByteString)ToLua.CheckObject(L, 1, typeof(Google.Protobuf.ByteString));
			Google.Protobuf.CodedInputStream o = obj.CreateCodedInput();
			ToLua.PushSealed(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Google.Protobuf.ByteString arg0 = (Google.Protobuf.ByteString)ToLua.ToObject(L, 1);
			Google.Protobuf.ByteString arg1 = (Google.Protobuf.ByteString)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Equals(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 2 && TypeChecker.CheckTypes<Google.Protobuf.ByteString>(L, 2))
			{
				Google.Protobuf.ByteString obj = (Google.Protobuf.ByteString)ToLua.CheckObject(L, 1, typeof(Google.Protobuf.ByteString));
				Google.Protobuf.ByteString arg0 = (Google.Protobuf.ByteString)ToLua.ToObject(L, 2);
				bool o = obj != null ? obj.Equals(arg0) : arg0 == null;
				LuaDLL.lua_pushboolean(L, o);
				return 1;
			}
			else if (count == 2 && TypeChecker.CheckTypes<object>(L, 2))
			{
				Google.Protobuf.ByteString obj = (Google.Protobuf.ByteString)ToLua.CheckObject(L, 1, typeof(Google.Protobuf.ByteString));
				object arg0 = ToLua.ToVarObject(L, 2);
				bool o = obj != null ? obj.Equals(arg0) : arg0 == null;
				LuaDLL.lua_pushboolean(L, o);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: Google.Protobuf.ByteString.Equals");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetHashCode(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Google.Protobuf.ByteString obj = (Google.Protobuf.ByteString)ToLua.CheckObject(L, 1, typeof(Google.Protobuf.ByteString));
			int o = obj.GetHashCode();
			LuaDLL.lua_pushinteger(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int CopyTo(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			Google.Protobuf.ByteString obj = (Google.Protobuf.ByteString)ToLua.CheckObject(L, 1, typeof(Google.Protobuf.ByteString));
			byte[] arg0 = ToLua.CheckByteBuffer(L, 2);
			int arg1 = (int)LuaDLL.luaL_checknumber(L, 3);
			obj.CopyTo(arg0, arg1);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int WriteTo(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Google.Protobuf.ByteString obj = (Google.Protobuf.ByteString)ToLua.CheckObject(L, 1, typeof(Google.Protobuf.ByteString));
			System.IO.Stream arg0 = (System.IO.Stream)ToLua.CheckObject<System.IO.Stream>(L, 2);
			obj.WriteTo(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_bytes(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Google.Protobuf.ByteString obj = (Google.Protobuf.ByteString)o;
			byte[] ret = obj.bytes;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index bytes on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Empty(IntPtr L)
	{
		try
		{
			ToLua.PushSealed(L, Google.Protobuf.ByteString.Empty);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Length(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Google.Protobuf.ByteString obj = (Google.Protobuf.ByteString)o;
			int ret = obj.Length;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index Length on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_IsEmpty(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Google.Protobuf.ByteString obj = (Google.Protobuf.ByteString)o;
			bool ret = obj.IsEmpty;
			LuaDLL.lua_pushboolean(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index IsEmpty on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_bytes(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Google.Protobuf.ByteString obj = (Google.Protobuf.ByteString)o;
			byte[] arg0 = ToLua.CheckByteBuffer(L, 2);
			obj.bytes = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index bytes on a nil value");
		}
	}
}

