//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class MongoDB_Bson_Serialization_Attributes_BsonKnownTypesAttributeWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(MongoDB.Bson.Serialization.Attributes.BsonKnownTypesAttribute), typeof(System.Attribute));
		L.RegFunction("Apply", Apply);
		L.RegFunction("New", _CreateMongoDB_Bson_Serialization_Attributes_BsonKnownTypesAttribute);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("KnownTypes", get_KnownTypes, null);
		L.RegFunction("getKnownTypes", get_KnownTypes);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateMongoDB_Bson_Serialization_Attributes_BsonKnownTypesAttribute(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 1 && TypeChecker.CheckTypes<System.Type>(L, 1))
			{
				System.Type arg0 = (System.Type)ToLua.ToObject(L, 1);
				MongoDB.Bson.Serialization.Attributes.BsonKnownTypesAttribute obj = new MongoDB.Bson.Serialization.Attributes.BsonKnownTypesAttribute(arg0);
				ToLua.PushObject(L, obj);
				return 1;
			}
			else if (TypeChecker.CheckParamsType<System.Type>(L, 1, count))
			{
				System.Type[] arg0 = ToLua.ToParamsObject<System.Type>(L, 1, count);
				MongoDB.Bson.Serialization.Attributes.BsonKnownTypesAttribute obj = new MongoDB.Bson.Serialization.Attributes.BsonKnownTypesAttribute(arg0);
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: MongoDB.Bson.Serialization.Attributes.BsonKnownTypesAttribute.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Apply(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			MongoDB.Bson.Serialization.Attributes.BsonKnownTypesAttribute obj = (MongoDB.Bson.Serialization.Attributes.BsonKnownTypesAttribute)ToLua.CheckObject<MongoDB.Bson.Serialization.Attributes.BsonKnownTypesAttribute>(L, 1);
			MongoDB.Bson.Serialization.BsonClassMap arg0 = (MongoDB.Bson.Serialization.BsonClassMap)ToLua.CheckObject<MongoDB.Bson.Serialization.BsonClassMap>(L, 2);
			obj.Apply(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_KnownTypes(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MongoDB.Bson.Serialization.Attributes.BsonKnownTypesAttribute obj = (MongoDB.Bson.Serialization.Attributes.BsonKnownTypesAttribute)o;
			System.Type[] ret = obj.KnownTypes;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index KnownTypes on a nil value");
		}
	}
}

