//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class MongoDB_Bson_IO_BsonReaderStateWrap
{
	public static void Register(LuaState L)
	{
		L.BeginEnum(typeof(MongoDB.Bson.IO.BsonReaderState));
		L.RegConstant("Initial", MongoDB.Bson.IO.BsonReaderState.Initial);
		L.RegConstant("Type", MongoDB.Bson.IO.BsonReaderState.Type);
		L.RegConstant("Name", MongoDB.Bson.IO.BsonReaderState.Name);
		L.RegConstant("Value", MongoDB.Bson.IO.BsonReaderState.Value);
		L.RegConstant("ScopeDocument", MongoDB.Bson.IO.BsonReaderState.ScopeDocument);
		L.RegConstant("EndOfDocument", MongoDB.Bson.IO.BsonReaderState.EndOfDocument);
		L.RegConstant("EndOfArray", MongoDB.Bson.IO.BsonReaderState.EndOfArray);
		L.RegConstant("Done", MongoDB.Bson.IO.BsonReaderState.Done);
		L.RegConstant("Closed", MongoDB.Bson.IO.BsonReaderState.Closed);
		L.EndEnum();
		TypeTraits<MongoDB.Bson.IO.BsonReaderState>.Check = CheckType;
		StackTraits<MongoDB.Bson.IO.BsonReaderState>.Push = Push;
	}

	static void Push(IntPtr L, MongoDB.Bson.IO.BsonReaderState arg)
	{
		ToLua.Push(L, arg);
	}

	static bool CheckType(IntPtr L, int pos)
	{
		return TypeChecker.CheckEnumType(typeof(MongoDB.Bson.IO.BsonReaderState), L, pos);
	}
}

