//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: FrameMessage.proto

using System;   
using System.Collections.Generic;
using ProtoBuf;
    
namespace DCET
{
  [ProtoContract]
  public partial class ObjectAddRequest
  { 
    [ProtoMember(1, IsRequired = true, DataFormat = DataFormat.TwosComplement)]
    public int RpcId { get; set; }
    
    [ProtoMember(2, IsRequired = true, DataFormat = DataFormat.TwosComplement)]
    public long ActorId { get; set; }
    
    [ProtoMember(3, IsRequired = true, DataFormat = DataFormat.TwosComplement)]
    public long Key { get; set; }
    
    [ProtoMember(4, IsRequired = true, DataFormat = DataFormat.TwosComplement)]
    public long InstanceId { get; set; }
    
  }
  
  [ProtoContract]
  public partial class ObjectAddResponse
  { 
    [ProtoMember(1, IsRequired = true, DataFormat = DataFormat.TwosComplement)]
    public int Error { get; set; }
    
    [ProtoMember(2, IsRequired = true, DataFormat = DataFormat.Default)]
    public string Message { get; set; }
    
    [ProtoMember(3, IsRequired = true, DataFormat = DataFormat.TwosComplement)]
    public int RpcId { get; set; }
    
  }
  
  [ProtoContract]
  public partial class ObjectLockRequest
  { 
    [ProtoMember(1, IsRequired = true, DataFormat = DataFormat.TwosComplement)]
    public int RpcId { get; set; }
    
    [ProtoMember(2, IsRequired = true, DataFormat = DataFormat.TwosComplement)]
    public long ActorId { get; set; }
    
    [ProtoMember(3, IsRequired = true, DataFormat = DataFormat.TwosComplement)]
    public long Key { get; set; }
    
    [ProtoMember(4, IsRequired = true, DataFormat = DataFormat.TwosComplement)]
    public long InstanceId { get; set; }
    
    [ProtoMember(5, IsRequired = true, DataFormat = DataFormat.TwosComplement)]
    public int Time { get; set; }
    
  }
  
  [ProtoContract]
  public partial class ObjectLockResponse
  { 
    [ProtoMember(1, IsRequired = true, DataFormat = DataFormat.TwosComplement)]
    public int Error { get; set; }
    
    [ProtoMember(2, IsRequired = true, DataFormat = DataFormat.Default)]
    public string Message { get; set; }
    
    [ProtoMember(3, IsRequired = true, DataFormat = DataFormat.TwosComplement)]
    public int RpcId { get; set; }
    
  }
  
  [ProtoContract]
  public partial class ObjectUnLockRequest
  { 
    [ProtoMember(1, IsRequired = true, DataFormat = DataFormat.TwosComplement)]
    public int RpcId { get; set; }
    
    [ProtoMember(2, IsRequired = true, DataFormat = DataFormat.TwosComplement)]
    public long ActorId { get; set; }
    
    [ProtoMember(3, IsRequired = true, DataFormat = DataFormat.TwosComplement)]
    public long Key { get; set; }
    
    [ProtoMember(4, IsRequired = true, DataFormat = DataFormat.TwosComplement)]
    public long OldInstanceId { get; set; }
    
    [ProtoMember(5, IsRequired = true, DataFormat = DataFormat.TwosComplement)]
    public long InstanceId { get; set; }
    
  }
  
  [ProtoContract]
  public partial class ObjectUnLockResponse
  { 
    [ProtoMember(1, IsRequired = true, DataFormat = DataFormat.TwosComplement)]
    public int Error { get; set; }
    
    [ProtoMember(2, IsRequired = true, DataFormat = DataFormat.Default)]
    public string Message { get; set; }
    
    [ProtoMember(3, IsRequired = true, DataFormat = DataFormat.TwosComplement)]
    public int RpcId { get; set; }
    
  }
  
  [ProtoContract]
  public partial class ObjectRemoveRequest
  { 
    [ProtoMember(1, IsRequired = true, DataFormat = DataFormat.TwosComplement)]
    public int RpcId { get; set; }
    
    [ProtoMember(2, IsRequired = true, DataFormat = DataFormat.TwosComplement)]
    public long ActorId { get; set; }
    
    [ProtoMember(3, IsRequired = true, DataFormat = DataFormat.TwosComplement)]
    public long Key { get; set; }
    
  }
  
  [ProtoContract]
  public partial class ObjectRemoveResponse
  { 
    [ProtoMember(1, IsRequired = true, DataFormat = DataFormat.TwosComplement)]
    public int Error { get; set; }
    
    [ProtoMember(2, IsRequired = true, DataFormat = DataFormat.Default)]
    public string Message { get; set; }
    
    [ProtoMember(3, IsRequired = true, DataFormat = DataFormat.TwosComplement)]
    public int RpcId { get; set; }
    
  }
  
  [ProtoContract]
  public partial class ObjectGetRequest
  { 
    [ProtoMember(1, IsRequired = true, DataFormat = DataFormat.TwosComplement)]
    public int RpcId { get; set; }
    
    [ProtoMember(2, IsRequired = true, DataFormat = DataFormat.TwosComplement)]
    public long ActorId { get; set; }
    
    [ProtoMember(3, IsRequired = true, DataFormat = DataFormat.TwosComplement)]
    public long Key { get; set; }
    
  }
  
  [ProtoContract]
  public partial class ObjectGetResponse
  { 
    [ProtoMember(1, IsRequired = true, DataFormat = DataFormat.TwosComplement)]
    public int Error { get; set; }
    
    [ProtoMember(2, IsRequired = true, DataFormat = DataFormat.Default)]
    public string Message { get; set; }
    
    [ProtoMember(3, IsRequired = true, DataFormat = DataFormat.TwosComplement)]
    public int RpcId { get; set; }
    
    [ProtoMember(4, IsRequired = true, DataFormat = DataFormat.TwosComplement)]
    public long InstanceId { get; set; }
    
  }
  
}