-- Generated by CSharp.lua Compiler
local System = System
local DCETModel = DCET.Model
local DCETHotfix
System.import(function (out)
  DCETHotfix = DCET.Hotfix
end)
System.namespace("DCET.Hotfix", function (namespace)
  namespace.class("Log", function (namespace)
    local Warning, Info, Error, Error1, Debug, Msg
    Warning = function (msg)
      DCETModel.Log.Warning(msg)
    end
    Info = function (msg)
      DCETModel.Log.Info(msg)
    end
    Error = function (e)
      DCETModel.Log.Error(DCETHotfix.ExceptionHelper.ToStr(e))
    end
    Error1 = function (msg)
      DCETModel.Log.Error(msg)
    end
    Debug = function (msg)
      DCETModel.Log.Debug(msg)
    end
    Msg = function (msg)
      Debug(DCETHotfix.Dumper.DumpAsString(msg, ""))
    end
    return {
      Warning = Warning,
      Info = Info,
      Error = Error,
      Error1 = Error1,
      Debug = Debug,
      Msg = Msg
    }
  end)
end)
