-- Generated by CSharp.lua Compiler
local System = System
local DCETHotfix
System.import(function (out)
  DCETHotfix = DCET.Hotfix
end)
System.namespace("DCET.Hotfix", function (namespace)
  namespace.class("ABInfoAwakeSystem", function (namespace)
    local Awake
    Awake = function (this, self, abName, a)
      self.AssetBundle = a
      self.Name = abName
      self.RefCount = 1
    end
    return {
      base = function (out)
        return {
          out.DCET.Hotfix.AwakeSystem_3(out.DCET.Hotfix.ABInfo, System.String, out.UnityEngine.AssetBundle)
        }
      end,
      Awake = Awake,
      __metadata__ = function (out)
        return {
          class = { 0x6, out.DCET.Hotfix.ObjectSystemAttribute() }
        }
      end
    }
  end)

  namespace.class("ABInfo", function (namespace)
    local Dispose, __ctor__
    __ctor__ = function (this)
      DCETHotfix.Entity.__ctor__(this)
    end
    Dispose = function (this)
      if this:getIsDisposed() then
        return
      end

      DCETHotfix.Entity.Dispose(this)

      --Log.Debug($"desdroy assetbundle: {this.Name}");

      if UnityEngine.op_Inequality(this.AssetBundle, nil) then
        this.AssetBundle:Unload(true)
      end

      this.RefCount = 0
      this.Name = ""
    end
    return {
      base = function (out)
        return {
          out.DCET.Hotfix.Entity
        }
      end,
      RefCount = 0,
      Dispose = Dispose,
      __ctor__ = __ctor__
    }
  end)
end)
