-- Generated by CSharp.lua Compiler
local System = System
local UnityEngine = UnityEngine
local DCETHotfix
System.import(function (out)
  DCETHotfix = DCET.Hotfix
end)
System.namespace("DCET.Hotfix", function (namespace)
  namespace.class("AssetsBundleLoaderAsyncSystem", function (namespace)
    local Update
    Update = function (this, self)
      self:Update()
    end
    return {
      base = function (out)
        return {
          out.DCET.Hotfix.UpdateSystem_1(out.DCET.Hotfix.AssetsBundleLoaderAsync)
        }
      end,
      Update = Update,
      __metadata__ = function (out)
        return {
          class = { 0x6, out.DCET.Hotfix.ObjectSystemAttribute() }
        }
      end
    }
  end)

  namespace.class("AssetsBundleLoaderAsync", function (namespace)
    local Update, Dispose, LoadAsync, __ctor__
    __ctor__ = function (this)
      DCETHotfix.Entity.__ctor__(this)
    end
    Update = function (this)
      if not this.request:getisDone() then
        return
      end

      local t = this.tcs
      t:SetResult(this.request:getassetBundle())
    end
    Dispose = function (this)
      if this:getIsDisposed() then
        return
      end
      DCETHotfix.Entity.Dispose(this)
    end
    LoadAsync = function (this, path)
      this.tcs = System.TaskCompletionSource()
      this.request = UnityEngine.AssetBundle.LoadFromFileAsync(path)
      return this.tcs:getTask()
    end
    return {
      base = function (out)
        return {
          out.DCET.Hotfix.Entity
        }
      end,
      Update = Update,
      Dispose = Dispose,
      LoadAsync = LoadAsync,
      __ctor__ = __ctor__
    }
  end)
end)
