-- Generated by CSharp.lua Compiler
local System = System
local ListType = System.List(System.Type)
System.namespace("DCET.Hotfix", function (namespace)
  namespace.class("Hotfix", function (namespace)
    local GetHotfixTypes, AddHotfixType, __ctor__
    __ctor__ = function (this)
      this.hotfixTypes = ListType()
    end
    GetHotfixTypes = function (this)
      return this.hotfixTypes
    end
    AddHotfixType = function (this, type)
      if type ~= nil and not this.hotfixTypes:Contains(type) then
        this.hotfixTypes:Add(type)
      end
    end
    return {
      base = function (out)
        return {
          out.DCET.Hotfix.Object
        }
      end,
      GetHotfixTypes = GetHotfixTypes,
      AddHotfixType = AddHotfixType,
      __ctor__ = __ctor__
    }
  end)
end)
