-- Generated by CSharp.lua Compiler
--------------------------------------------------------------------------------
-- <auto-generated>
--     This code was generated by a tool.
--
--     Changes to this file may cause incorrect behavior and will be lost if
--     the code is regenerated.
-- </auto-generated>
--------------------------------------------------------------------------------
-- Generated from: CommonPrototype.proto
local System = System
local CSharpLuaSettingProto
local ListValuePairProto
System.import(function (out)
  CSharpLuaSettingProto = CSharpLua.Project.Protocol.SettingProto
  ListValuePairProto = System.List(CSharpLuaSettingProto.ValuePairProto)
end)
System.namespace("CSharpLua.Project.Protocol", function (namespace)
  namespace.class("SettingProto", function (namespace)
    local __ctor__
    namespace.class("ValuePairProto", function (namespace)
      return {
        base = function (out)
          return {
            out.ProtoBuf.IProtocol
          }
        end,
        __metadata__ = function (out)
          return {
            properties = {
              { "Key", 0x6, System.String, System.apply(out.ProtoBuf.ProtoMemberAttribute(1), function (default) default:setIsRequired(true)default:setDataFormat(0 --[[DataFormat.Default]]) end) },
              { "Value", 0x6, System.String, System.apply(out.ProtoBuf.ProtoMemberAttribute(2), function (default) default:setIsRequired(true)default:setDataFormat(0 --[[DataFormat.Default]]) end) }
            },
            class = { 0x6, out.ProtoBuf.ProtoContractAttribute() }
          }
        end
      }
    end)
    __ctor__ = function (this)
      this.Values = ListValuePairProto()
    end
    return {
      base = function (out)
        return {
          out.ProtoBuf.IProtocol
        }
      end,
      SettingsMark = 0,
      __ctor__ = __ctor__,
      __metadata__ = function (out)
        return {
          properties = {
            { "SettingsMark", 0x6, System.Int32, System.apply(out.ProtoBuf.ProtoMemberAttribute(2), function (default) default:setIsRequired(true)default:setDataFormat(2 --[[DataFormat.TwosComplement]]) end) },
            { "Values", 0x6, System.List(out.CSharpLua.Project.Protocol.SettingProto.ValuePairProto), System.apply(out.ProtoBuf.ProtoMemberAttribute(1), function (default) default:setDataFormat(0 --[[DataFormat.Default]]) end) }
          },
          class = { 0x6, out.ProtoBuf.ProtoContractAttribute() }
        }
      end
    }
  end)
end)
