-- Generated by CSharp.lua Compiler
--[[ Copyright 2010-present MongoDB Inc.
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
]]
local System = System
System.namespace("MongoDB.Bson.IO", function (namespace)
  -- <summary>
  -- Represents a bookmark that can be used to return a reader to the current position and state.
  -- </summary>
  namespace.class("BsonReaderBookmark", function (namespace)
    local getState, getCurrentBsonType, getCurrentName, __ctor__
    -- <summary>
    -- Initializes a new instance of the BsonReaderBookmark class.
    -- </summary>
    -- <param name="currentBsonType">The current BSON type.</param>
    -- <param name="currentName">The name of the current element.</param>
    __ctor__ = function (this, state, currentBsonType, currentName)
      this._state = state
      this._currentBsonType = currentBsonType
      this._currentName = currentName
    end
    getState = function (this)
      return this._state
    end
    getCurrentBsonType = function (this)
      return this._currentBsonType
    end
    getCurrentName = function (this)
      return this._currentName
    end
    return {
      _state = 0,
      _currentBsonType = 0,
      getState = getState,
      getCurrentBsonType = getCurrentBsonType,
      getCurrentName = getCurrentName,
      __ctor__ = __ctor__
    }
  end)
end)
