-- Generated by CSharp.lua Compiler
--[[ Copyright 2010-present MongoDB Inc.
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
]]
local System = System
local MongoDBBson
local MongoDBBsonIO
System.import(function (out)
  MongoDBBson = MongoDB.Bson
  MongoDBBsonIO = MongoDB.Bson.IO
end)
System.namespace("MongoDB.Bson.IO", function (namespace)
  -- <summary>
  -- Represents settings for a BsonBinaryWriter.
  -- </summary>
  namespace.class("BsonBinaryWriterSettings", function (namespace)
    local __defaults, getDefaults, setDefaults, getEncoding, setEncoding, getFixOldBinarySubTypeOnOutput, setFixOldBinarySubTypeOnOutput, getMaxDocumentSize, 
    setMaxDocumentSize, Clone1, CloneImplementation, class, __ctor__
    -- <summary>
    -- Initializes a new instance of the BsonBinaryWriterSettings class.
    -- </summary>
    __ctor__ = function (this)
      this._encoding = MongoDBBsonIO.Utf8Encodings.getStrict()
      this._maxDocumentSize = MongoDBBson.BsonDefaults.getMaxDocumentSize()
      MongoDBBsonIO.BsonWriterSettings.__ctor__[1](this)
    end
    getDefaults = function ()
      if __defaults == nil then
        __defaults = class()
      end
      return __defaults
    end
    setDefaults = function (value)
      __defaults = value
    end
    getEncoding = function (this)
      return this._encoding
    end
    setEncoding = function (this, value)
      if value == nil then
        System.throw(System.ArgumentNullException("value"))
      end
      if this:getIsFrozen() then
        System.throw(System.InvalidOperationException("BsonBinaryWriterSettings is frozen."))
      end
      this._encoding = value
    end
    getFixOldBinarySubTypeOnOutput = function (this)
      return this._fixOldBinarySubTypeOnOutput
    end
    setFixOldBinarySubTypeOnOutput = function (this, value)
      if this:getIsFrozen() then
        System.throw(System.InvalidOperationException("BsonBinaryWriterSettings is frozen."))
      end
      this._fixOldBinarySubTypeOnOutput = value
    end
    getMaxDocumentSize = function (this)
      return this._maxDocumentSize
    end
    setMaxDocumentSize = function (this, value)
      if this:getIsFrozen() then
        System.throw(System.InvalidOperationException("BsonBinaryWriterSettings is frozen."))
      end
      this._maxDocumentSize = value
    end
    -- <summary>
    -- Creates a clone of the settings.
    -- </summary>
    Clone1 = function (this)
      return System.cast(class, this:CloneImplementation())
    end
    -- <summary>
    -- Creates a clone of the settings.
    -- </summary>
    CloneImplementation = function (this)
      local default = class()
      setEncoding(default, this._encoding)
      setFixOldBinarySubTypeOnOutput(default, this._fixOldBinarySubTypeOnOutput)
      default:setGuidRepresentation(this:getGuidRepresentation())
      setMaxDocumentSize(default, this._maxDocumentSize)
      default:setMaxSerializationDepth(this:getMaxSerializationDepth())
      local clone = default
      return clone
    end
    class = {
      base = function (out)
        return {
          out.MongoDB.Bson.IO.BsonWriterSettings
        }
      end,
      _fixOldBinarySubTypeOnOutput = true,
      getDefaults = getDefaults,
      setDefaults = setDefaults,
      getEncoding = getEncoding,
      setEncoding = setEncoding,
      getFixOldBinarySubTypeOnOutput = getFixOldBinarySubTypeOnOutput,
      setFixOldBinarySubTypeOnOutput = setFixOldBinarySubTypeOnOutput,
      getMaxDocumentSize = getMaxDocumentSize,
      setMaxDocumentSize = setMaxDocumentSize,
      Clone1 = Clone1,
      CloneImplementation = CloneImplementation,
      __ctor__ = __ctor__,
      __metadata__ = function (out)
        return {
          fields = {
            { "__defaults", 0x9, class },
            { "_encoding", 0x1, System.Text.UTF8Encoding },
            { "_fixOldBinarySubTypeOnOutput", 0x1, System.Boolean },
            { "_maxDocumentSize", 0x1, System.Int32 }
          },
          properties = {
            { "Defaults", 0x10E, class, getDefaults, setDefaults },
            { "Encoding", 0x106, System.Text.UTF8Encoding, getEncoding, setEncoding },
            { "FixOldBinarySubTypeOnOutput", 0x106, System.Boolean, getFixOldBinarySubTypeOnOutput, setFixOldBinarySubTypeOnOutput },
            { "MaxDocumentSize", 0x106, System.Int32, getMaxDocumentSize, setMaxDocumentSize }
          },
          class = { 0x6, System.SerializableAttribute() }
        }
      end
    }
    return class
  end)
end)
