-- Generated by CSharp.lua Compiler
local System = System
System.namespace("DCET.Hotfix", function (namespace)
  namespace.class("ExceptionHelper", function (namespace)
    local ToStr
    ToStr = function (exception)
      return exception:ToString()
    end
    return {
      ToStr = ToStr
    }
  end)
end)
