-- Generated by CSharp.lua Compiler
--[[ Copyright 2010-present MongoDB Inc.
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
]]
local System = System
local ArrayString = System.Array(System.String)
local MongoDBConventions
local ListIConvention
System.import(function (out)
  MongoDBConventions = MongoDB.Bson.Serialization.Conventions
  ListIConvention = System.List(MongoDBConventions.IConvention)
end)
System.namespace("MongoDB.Bson.Serialization.Conventions", function (namespace)
  -- <summary>
  -- Convention pack of defaults.
  -- </summary>
  namespace.class("DefaultConventionPack", function (namespace)
    local __defaultConventionPack, getInstance, getConventions, class, static, __ctor__
    static = function (this)
      __defaultConventionPack = class()
    end
    -- <summary>
    -- Initializes a new instance of the <see cref="DefaultConventionPack" /> class.
    -- </summary>
    __ctor__ = function (this)
      local default = ListIConvention()
      default:Add(MongoDBConventions.ReadWriteMemberFinderConvention())
      default:Add(MongoDBConventions.NamedIdMemberConvention(ArrayString("Id", "id", "_id")))
      default:Add(System.new(MongoDBConventions.NamedExtraElementsMemberConvention, 2, ArrayString("ExtraElements")))
      default:Add(MongoDBConventions.IgnoreExtraElementsConvention(false))
      default:Add(MongoDBConventions.ImmutableTypeClassMapConvention())
      default:Add(MongoDBConventions.NamedParameterCreatorMapConvention())
      default:Add(MongoDBConventions.StringObjectIdIdGeneratorConvention())
      default:Add(MongoDBConventions.LookupIdGeneratorConvention())
      this._conventions = default
    end
    getInstance = function ()
      return __defaultConventionPack
    end
    getConventions = function (this)
      return this._conventions
    end
    class = {
      base = function (out)
        return {
          out.MongoDB.Bson.Serialization.Conventions.IConventionPack
        }
      end,
      getInstance = getInstance,
      getConventions = getConventions,
      static = static,
      __ctor__ = __ctor__
    }
    return class
  end)
end)
