-- Generated by CSharp.lua Compiler
--[[ Copyright 2010-present MongoDB Inc.
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
]]
local System = System
local MongoDBConventions
System.import(function (out)
  MongoDBConventions = MongoDB.Bson.Serialization.Conventions
end)
System.namespace("MongoDB.Bson.Serialization.Conventions", function (namespace)
  -- <summary>
  -- A class map convention that wraps a delegate.
  -- </summary>
  namespace.class("DelegateClassMapConvention", function (namespace)
    local Apply, __ctor__
    -- <summary>
    -- Initializes a new instance of the <see cref="DelegateClassMapConvention" /> class.
    -- </summary>
    -- <param name="action">The delegate.</param>
    __ctor__ = function (this, name, action)
      MongoDBConventions.ConventionBase.__ctor__[2](this, name)
      if action == nil then
        System.throw(System.ArgumentNullException("action"))
      end
      this._action = action
    end
    -- <summary>
    -- Applies a modification to the class map.
    -- </summary>
    Apply = function (this, classMap)
      this._action(classMap)
    end
    return {
      base = function (out)
        return {
          out.MongoDB.Bson.Serialization.Conventions.ConventionBase,
          out.MongoDB.Bson.Serialization.Conventions.IClassMapConvention
        }
      end,
      Apply = Apply,
      __ctor__ = __ctor__
    }
  end)
end)
