-- Generated by CSharp.lua Compiler
--[[ Copyright 2010-present MongoDB Inc.
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
]]
local System = System
local Linq = System.Linq.Enumerable
local SystemReflection = System.Reflection
local MongoDBBson
local MongoDBAttributes
System.import(function (out)
  MongoDBBson = MongoDB.Bson
  MongoDBAttributes = MongoDB.Bson.Serialization.Attributes
end)
System.namespace("MongoDB.Bson.Serialization", function (namespace)
  -- <summary>
  -- Provides serializers based on an attribute.
  -- </summary>
  namespace.class("AttributedSerializationProvider", function (namespace)
    local GetSerializer1
    GetSerializer1 = function (this, type, serializerRegistry)
      if type == nil then
        System.throw(System.ArgumentNullException("type"))
      end
      local typeInfo = SystemReflection.IntrospectionExtensions.GetTypeInfo(type)
      if typeInfo:getIsGenericType() and typeInfo:getContainsGenericParameters() then
        local message = System.String.Format("Generic type {0} has unassigned type parameters.", MongoDBBson.BsonUtils.GetFriendlyTypeName(type))
        System.throw(System.ArgumentException(message, "type"))
      end

      local serializerAttributes = Linq.ToArray(SystemReflection.CustomAttributeExtensions.GetCustomAttributes(typeInfo, false, MongoDBAttributes.BsonSerializerAttribute))
      if #serializerAttributes == 1 then
        local serializerAttribute = serializerAttributes:get(0)
        return serializerAttribute:CreateSerializer(type)
      end

      return nil
    end
    return {
      base = function (out)
        return {
          out.MongoDB.Bson.Serialization.BsonSerializationProviderBase
        }
      end,
      GetSerializer1 = GetSerializer1
    }
  end)
end)
