-- Generated by CSharp.lua Compiler
local System = System
local DCETHotfix = DCET.Hotfix
System.namespace("DCET.Hotfix", function (namespace)
  -- 分发数值监听
  namespace.class("TestHotfixSubscribMonoEvent_LogString", function (namespace)
    local Run
    Run = function (this, info)
      DCETHotfix.Log.Info(info)
    end
    return {
      base = function (out)
        return {
          out.DCET.Hotfix.AEvent_1(System.String)
        }
      end,
      Run = Run
    }
  end)
end)
