-- Generated by CSharp.lua Compiler
local System = System
local SystemNet = System.Net
local ListString = System.List(System.String)
System.namespace("DCET", function (namespace)
  namespace.class("NetHelper", function (namespace)
    local GetAddressIPs
    GetAddressIPs = function ()
      --获取本地的IP地址
      local addressIPs = ListString()
      for _, address in System.each(SystemNet.Dns.GetHostEntry(SystemNet.Dns.GetHostName()):getAddressList()) do
        addressIPs:Add(address:ToString())
      end
      return addressIPs:ToArray()
    end
    return {
      GetAddressIPs = GetAddressIPs
    }
  end)
end)
