-- Generated by CSharp.lua Compiler
local System = System
local DCETHotfix = DCET.Hotfix
local DCETModel = DCET.Model
local FairyGUI = FairyGUI
local DictStringUIPackage = System.Dictionary(System.String, FairyGUI.UIPackage)
System.namespace("DCET.Hotfix", function (namespace)
  -- <summary>
  -- 管理所有UI Package
  -- </summary>
  namespace.class("FUIPackageComponent", function (namespace)
    local FUI_PACKAGE_DIR, AddPackage, AddPackageAsync, RemovePackage, class, __ctor__
    __ctor__ = function (this)
      this.packages = DictStringUIPackage()
      DCETHotfix.Entity.__ctor__(this)
    end
    FUI_PACKAGE_DIR = "Assets/Bundles/FUI"
    AddPackage = function (this, type)
      if DCETModel.Define.IsEditorMode then
        local uiPackage = FairyGUI.UIPackage.AddPackage(class.FUI_PACKAGE_DIR .. "/" .. type)
        this.packages:AddKeyValue(type, uiPackage)
      else
        local uiBundleDesName = DCETModel.AssetBundleHelper.StringToAB(type .. "_fui")
        local uiBundleResName = DCETModel.AssetBundleHelper.StringToAB(type)
        local resourcesComponent = DCETHotfix.Game.getScene():GetComponent(DCETHotfix.ResourcesComponent)
        resourcesComponent:LoadBundle(uiBundleDesName)
        resourcesComponent:LoadBundle(uiBundleResName)

        local desAssetBundle = resourcesComponent:GetAssetBundle(uiBundleDesName)
        local resAssetBundle = resourcesComponent:GetAssetBundle(uiBundleResName)
        local uiPackage = FairyGUI.UIPackage.AddPackage(desAssetBundle, resAssetBundle)
        this.packages:AddKeyValue(type, uiPackage)
      end
    end
    AddPackageAsync = function (this, type)
      return System.async(function (async, this, type)
        if DCETModel.Define.IsEditorMode then
          async:await(System.Task.getCompletedTask())

          local uiPackage = FairyGUI.UIPackage.AddPackage(class.FUI_PACKAGE_DIR .. "/" .. type)

          this.packages:AddKeyValue(type, uiPackage)
        else
          local uiBundleDesName = DCETModel.AssetBundleHelper.StringToAB(type .. "_fui")
          local uiBundleResName = DCETModel.AssetBundleHelper.StringToAB(type)
          local resourcesComponent = DCETHotfix.Game.getScene():GetComponent(DCETHotfix.ResourcesComponent)
          async:await(resourcesComponent:LoadBundleAsync(uiBundleDesName))
          async:await(resourcesComponent:LoadBundleAsync(uiBundleResName))

          local desAssetBundle = resourcesComponent:GetAssetBundle(uiBundleDesName)
          local resAssetBundle = resourcesComponent:GetAssetBundle(uiBundleResName)
          local uiPackage = FairyGUI.UIPackage.AddPackage(desAssetBundle, resAssetBundle)

          this.packages:AddKeyValue(type, uiPackage)
        end
      end, nil, this, type)
    end
    RemovePackage = function (this, type)
      local package

      local default
      default, package = this.packages:TryGetValue(type)
      if default then
        local p = FairyGUI.UIPackage.GetByName(package:getname())

        if p ~= nil then
          FairyGUI.UIPackage.RemovePackage(package:getname())
        end

        this.packages:RemoveKey(package:getname())
      end

      if not DCETModel.Define.IsEditorMode then
        local uiBundleDesName = DCETModel.AssetBundleHelper.StringToAB(type .. "_fui")
        local uiBundleResName = DCETModel.AssetBundleHelper.StringToAB(type)
        DCETHotfix.Game.getScene():GetComponent(DCETHotfix.ResourcesComponent):UnloadBundle(uiBundleDesName)
        DCETHotfix.Game.getScene():GetComponent(DCETHotfix.ResourcesComponent):UnloadBundle(uiBundleResName)
      end
    end
    class = {
      base = function (out)
        return {
          out.DCET.Hotfix.Entity
        }
      end,
      FUI_PACKAGE_DIR = FUI_PACKAGE_DIR,
      AddPackage = AddPackage,
      AddPackageAsync = AddPackageAsync,
      RemovePackage = RemovePackage,
      __ctor__ = __ctor__
    }
    return class
  end)
end)
