-- Generated by CSharp.lua Compiler
return function (path)
  return System.init({
    path = path,
    files = {
      "FUI",
      "FUIComponent",
      "FUIPackageComponent",
      "FUIStackComponent",
      "GComponentHelper",
      "GObjectHelper"
    },
    types = {
      "DCET.Hotfix.FUI",
      "DCET.Hotfix.FUIComponent",
      "DCET.Hotfix.FUIAwakeSystem",
      "DCET.Hotfix.FUIComponentAwakeSystem",
      "DCET.Hotfix.FUIPackageComponent",
      "DCET.Hotfix.FUIStackComponent",
      "DCET.Hotfix.GComponentHelper",
      "DCET.Hotfix.GObjectHelper"
    }
  })
end
