//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class MongoDB_Bson_BsonBinarySubTypeWrap
{
	public static void Register(LuaState L)
	{
		L.BeginEnum(typeof(MongoDB.Bson.BsonBinarySubType));
		L.RegConstant("Binary", MongoDB.Bson.BsonBinarySubType.Binary);
		L.RegConstant("Function", MongoDB.Bson.BsonBinarySubType.Function);
		L.RegConstant("UuidLegacy", MongoDB.Bson.BsonBinarySubType.UuidLegacy);
		L.RegConstant("UuidStandard", MongoDB.Bson.BsonBinarySubType.UuidStandard);
		L.RegConstant("MD5", MongoDB.Bson.BsonBinarySubType.MD5);
		L.RegConstant("UserDefined", MongoDB.Bson.BsonBinarySubType.UserDefined);
		L.EndEnum();
		TypeTraits<MongoDB.Bson.BsonBinarySubType>.Check = CheckType;
		StackTraits<MongoDB.Bson.BsonBinarySubType>.Push = Push;
	}

	static void Push(IntPtr L, MongoDB.Bson.BsonBinarySubType arg)
	{
		ToLua.Push(L, arg);
	}

	static bool CheckType(IntPtr L, int pos)
	{
		return TypeChecker.CheckEnumType(typeof(MongoDB.Bson.BsonBinarySubType), L, pos);
	}
}

