//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class MongoDB_Bson_Serialization_IdGenerators_AscendingGuidGeneratorWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(MongoDB.Bson.Serialization.IdGenerators.AscendingGuidGenerator), typeof(System.Object));
		L.RegFunction("GenerateId", GenerateId);
		L.RegFunction("IsEmpty", IsEmpty);
		L.RegFunction("New", _CreateMongoDB_Bson_Serialization_IdGenerators_AscendingGuidGenerator);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("Instance", get_Instance, null);
		L.RegFunction("getInstance", get_Instance);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateMongoDB_Bson_Serialization_IdGenerators_AscendingGuidGenerator(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				MongoDB.Bson.Serialization.IdGenerators.AscendingGuidGenerator obj = new MongoDB.Bson.Serialization.IdGenerators.AscendingGuidGenerator();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: MongoDB.Bson.Serialization.IdGenerators.AscendingGuidGenerator.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GenerateId(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 3)
			{
				MongoDB.Bson.Serialization.IdGenerators.AscendingGuidGenerator obj = (MongoDB.Bson.Serialization.IdGenerators.AscendingGuidGenerator)ToLua.CheckObject<MongoDB.Bson.Serialization.IdGenerators.AscendingGuidGenerator>(L, 1);
				object arg0 = ToLua.ToVarObject(L, 2);
				object arg1 = ToLua.ToVarObject(L, 3);
				object o = obj.GenerateId(arg0, arg1);
				ToLua.Push(L, o);
				return 1;
			}
			else if (count == 4)
			{
				MongoDB.Bson.Serialization.IdGenerators.AscendingGuidGenerator obj = (MongoDB.Bson.Serialization.IdGenerators.AscendingGuidGenerator)ToLua.CheckObject<MongoDB.Bson.Serialization.IdGenerators.AscendingGuidGenerator>(L, 1);
				long arg0 = LuaDLL.tolua_checkint64(L, 2);
				byte[] arg1 = ToLua.CheckByteBuffer(L, 3);
				int arg2 = (int)LuaDLL.luaL_checknumber(L, 4);
				object o = obj.GenerateId(arg0, arg1, arg2);
				ToLua.Push(L, o);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: MongoDB.Bson.Serialization.IdGenerators.AscendingGuidGenerator.GenerateId");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IsEmpty(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			MongoDB.Bson.Serialization.IdGenerators.AscendingGuidGenerator obj = (MongoDB.Bson.Serialization.IdGenerators.AscendingGuidGenerator)ToLua.CheckObject<MongoDB.Bson.Serialization.IdGenerators.AscendingGuidGenerator>(L, 1);
			object arg0 = ToLua.ToVarObject(L, 2);
			bool o = obj.IsEmpty(arg0);
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Instance(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, MongoDB.Bson.Serialization.IdGenerators.AscendingGuidGenerator.Instance);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

