//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class MongoDB_Bson_Serialization_Attributes_BsonIgnoreIfDefaultAttributeWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(MongoDB.Bson.Serialization.Attributes.BsonIgnoreIfDefaultAttribute), typeof(System.Attribute));
		L.RegFunction("Apply", Apply);
		L.RegFunction("New", _CreateMongoDB_Bson_Serialization_Attributes_BsonIgnoreIfDefaultAttribute);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("Value", get_Value, null);
		L.RegFunction("getValue", get_Value);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateMongoDB_Bson_Serialization_Attributes_BsonIgnoreIfDefaultAttribute(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				MongoDB.Bson.Serialization.Attributes.BsonIgnoreIfDefaultAttribute obj = new MongoDB.Bson.Serialization.Attributes.BsonIgnoreIfDefaultAttribute();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else if (count == 1)
			{
				bool arg0 = LuaDLL.luaL_checkboolean(L, 1);
				MongoDB.Bson.Serialization.Attributes.BsonIgnoreIfDefaultAttribute obj = new MongoDB.Bson.Serialization.Attributes.BsonIgnoreIfDefaultAttribute(arg0);
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: MongoDB.Bson.Serialization.Attributes.BsonIgnoreIfDefaultAttribute.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Apply(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			MongoDB.Bson.Serialization.Attributes.BsonIgnoreIfDefaultAttribute obj = (MongoDB.Bson.Serialization.Attributes.BsonIgnoreIfDefaultAttribute)ToLua.CheckObject<MongoDB.Bson.Serialization.Attributes.BsonIgnoreIfDefaultAttribute>(L, 1);
			MongoDB.Bson.Serialization.BsonMemberMap arg0 = (MongoDB.Bson.Serialization.BsonMemberMap)ToLua.CheckObject<MongoDB.Bson.Serialization.BsonMemberMap>(L, 2);
			obj.Apply(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Value(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MongoDB.Bson.Serialization.Attributes.BsonIgnoreIfDefaultAttribute obj = (MongoDB.Bson.Serialization.Attributes.BsonIgnoreIfDefaultAttribute)o;
			bool ret = obj.Value;
			LuaDLL.lua_pushboolean(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index Value on a nil value");
		}
	}
}

