//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class Pathfinding_GraphUpdateSceneWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(Pathfinding.GraphUpdateScene), typeof(Pathfinding.GraphModifier));
		L.RegFunction("Start", Start);
		L.RegFunction("OnPostScan", OnPostScan);
		L.RegFunction("InvertSettings", InvertSettings);
		L.RegFunction("RecalcConvex", RecalcConvex);
		L.RegFunction("GetBounds", GetBounds);
		L.RegFunction("Apply", Apply);
		L.RegFunction("DisableLegacyMode", DisableLegacyMode);
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("points", get_points, set_points);
		L.RegVar("convex", get_convex, set_convex);
		L.RegVar("minBoundsHeight", get_minBoundsHeight, set_minBoundsHeight);
		L.RegVar("penaltyDelta", get_penaltyDelta, set_penaltyDelta);
		L.RegVar("modifyWalkability", get_modifyWalkability, set_modifyWalkability);
		L.RegVar("setWalkability", get_setWalkability, set_setWalkability);
		L.RegVar("applyOnStart", get_applyOnStart, set_applyOnStart);
		L.RegVar("applyOnScan", get_applyOnScan, set_applyOnScan);
		L.RegVar("updatePhysics", get_updatePhysics, set_updatePhysics);
		L.RegVar("resetPenaltyOnPhysics", get_resetPenaltyOnPhysics, set_resetPenaltyOnPhysics);
		L.RegVar("updateErosion", get_updateErosion, set_updateErosion);
		L.RegVar("modifyTag", get_modifyTag, set_modifyTag);
		L.RegVar("setTag", get_setTag, set_setTag);
		L.RegVar("legacyMode", get_legacyMode, set_legacyMode);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Start(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Pathfinding.GraphUpdateScene obj = (Pathfinding.GraphUpdateScene)ToLua.CheckObject<Pathfinding.GraphUpdateScene>(L, 1);
			obj.Start();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnPostScan(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Pathfinding.GraphUpdateScene obj = (Pathfinding.GraphUpdateScene)ToLua.CheckObject<Pathfinding.GraphUpdateScene>(L, 1);
			obj.OnPostScan();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int InvertSettings(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Pathfinding.GraphUpdateScene obj = (Pathfinding.GraphUpdateScene)ToLua.CheckObject<Pathfinding.GraphUpdateScene>(L, 1);
			obj.InvertSettings();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int RecalcConvex(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Pathfinding.GraphUpdateScene obj = (Pathfinding.GraphUpdateScene)ToLua.CheckObject<Pathfinding.GraphUpdateScene>(L, 1);
			obj.RecalcConvex();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetBounds(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Pathfinding.GraphUpdateScene obj = (Pathfinding.GraphUpdateScene)ToLua.CheckObject<Pathfinding.GraphUpdateScene>(L, 1);
			UnityEngine.Bounds o = obj.GetBounds();
			ToLua.Push(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Apply(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Pathfinding.GraphUpdateScene obj = (Pathfinding.GraphUpdateScene)ToLua.CheckObject<Pathfinding.GraphUpdateScene>(L, 1);
			obj.Apply();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int DisableLegacyMode(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Pathfinding.GraphUpdateScene obj = (Pathfinding.GraphUpdateScene)ToLua.CheckObject<Pathfinding.GraphUpdateScene>(L, 1);
			obj.DisableLegacyMode();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_points(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Pathfinding.GraphUpdateScene obj = (Pathfinding.GraphUpdateScene)o;
			UnityEngine.Vector3[] ret = obj.points;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index points on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_convex(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Pathfinding.GraphUpdateScene obj = (Pathfinding.GraphUpdateScene)o;
			bool ret = obj.convex;
			LuaDLL.lua_pushboolean(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index convex on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_minBoundsHeight(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Pathfinding.GraphUpdateScene obj = (Pathfinding.GraphUpdateScene)o;
			float ret = obj.minBoundsHeight;
			LuaDLL.lua_pushnumber(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index minBoundsHeight on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_penaltyDelta(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Pathfinding.GraphUpdateScene obj = (Pathfinding.GraphUpdateScene)o;
			int ret = obj.penaltyDelta;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index penaltyDelta on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_modifyWalkability(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Pathfinding.GraphUpdateScene obj = (Pathfinding.GraphUpdateScene)o;
			bool ret = obj.modifyWalkability;
			LuaDLL.lua_pushboolean(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index modifyWalkability on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_setWalkability(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Pathfinding.GraphUpdateScene obj = (Pathfinding.GraphUpdateScene)o;
			bool ret = obj.setWalkability;
			LuaDLL.lua_pushboolean(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index setWalkability on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_applyOnStart(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Pathfinding.GraphUpdateScene obj = (Pathfinding.GraphUpdateScene)o;
			bool ret = obj.applyOnStart;
			LuaDLL.lua_pushboolean(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index applyOnStart on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_applyOnScan(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Pathfinding.GraphUpdateScene obj = (Pathfinding.GraphUpdateScene)o;
			bool ret = obj.applyOnScan;
			LuaDLL.lua_pushboolean(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index applyOnScan on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_updatePhysics(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Pathfinding.GraphUpdateScene obj = (Pathfinding.GraphUpdateScene)o;
			bool ret = obj.updatePhysics;
			LuaDLL.lua_pushboolean(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index updatePhysics on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_resetPenaltyOnPhysics(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Pathfinding.GraphUpdateScene obj = (Pathfinding.GraphUpdateScene)o;
			bool ret = obj.resetPenaltyOnPhysics;
			LuaDLL.lua_pushboolean(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index resetPenaltyOnPhysics on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_updateErosion(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Pathfinding.GraphUpdateScene obj = (Pathfinding.GraphUpdateScene)o;
			bool ret = obj.updateErosion;
			LuaDLL.lua_pushboolean(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index updateErosion on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_modifyTag(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Pathfinding.GraphUpdateScene obj = (Pathfinding.GraphUpdateScene)o;
			bool ret = obj.modifyTag;
			LuaDLL.lua_pushboolean(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index modifyTag on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_setTag(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Pathfinding.GraphUpdateScene obj = (Pathfinding.GraphUpdateScene)o;
			int ret = obj.setTag;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index setTag on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_legacyMode(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Pathfinding.GraphUpdateScene obj = (Pathfinding.GraphUpdateScene)o;
			bool ret = obj.legacyMode;
			LuaDLL.lua_pushboolean(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index legacyMode on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_points(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Pathfinding.GraphUpdateScene obj = (Pathfinding.GraphUpdateScene)o;
			UnityEngine.Vector3[] arg0 = ToLua.CheckStructArray<UnityEngine.Vector3>(L, 2);
			obj.points = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index points on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_convex(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Pathfinding.GraphUpdateScene obj = (Pathfinding.GraphUpdateScene)o;
			bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
			obj.convex = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index convex on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_minBoundsHeight(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Pathfinding.GraphUpdateScene obj = (Pathfinding.GraphUpdateScene)o;
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
			obj.minBoundsHeight = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index minBoundsHeight on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_penaltyDelta(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Pathfinding.GraphUpdateScene obj = (Pathfinding.GraphUpdateScene)o;
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			obj.penaltyDelta = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index penaltyDelta on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_modifyWalkability(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Pathfinding.GraphUpdateScene obj = (Pathfinding.GraphUpdateScene)o;
			bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
			obj.modifyWalkability = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index modifyWalkability on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_setWalkability(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Pathfinding.GraphUpdateScene obj = (Pathfinding.GraphUpdateScene)o;
			bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
			obj.setWalkability = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index setWalkability on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_applyOnStart(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Pathfinding.GraphUpdateScene obj = (Pathfinding.GraphUpdateScene)o;
			bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
			obj.applyOnStart = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index applyOnStart on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_applyOnScan(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Pathfinding.GraphUpdateScene obj = (Pathfinding.GraphUpdateScene)o;
			bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
			obj.applyOnScan = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index applyOnScan on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_updatePhysics(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Pathfinding.GraphUpdateScene obj = (Pathfinding.GraphUpdateScene)o;
			bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
			obj.updatePhysics = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index updatePhysics on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_resetPenaltyOnPhysics(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Pathfinding.GraphUpdateScene obj = (Pathfinding.GraphUpdateScene)o;
			bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
			obj.resetPenaltyOnPhysics = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index resetPenaltyOnPhysics on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_updateErosion(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Pathfinding.GraphUpdateScene obj = (Pathfinding.GraphUpdateScene)o;
			bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
			obj.updateErosion = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index updateErosion on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_modifyTag(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Pathfinding.GraphUpdateScene obj = (Pathfinding.GraphUpdateScene)o;
			bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
			obj.modifyTag = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index modifyTag on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_setTag(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Pathfinding.GraphUpdateScene obj = (Pathfinding.GraphUpdateScene)o;
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			obj.setTag = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index setTag on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_legacyMode(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Pathfinding.GraphUpdateScene obj = (Pathfinding.GraphUpdateScene)o;
			bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
			obj.legacyMode = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index legacyMode on a nil value");
		}
	}
}

