//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class AstarPath_AstarDistributionWrap
{
	public static void Register(LuaState L)
	{
		L.BeginEnum(typeof(AstarPath.AstarDistribution));
		L.RegConstant("WebsiteDownload", AstarPath.AstarDistribution.WebsiteDownload);
		L.RegConstant("AssetStore", AstarPath.AstarDistribution.AssetStore);
		L.EndEnum();
		TypeTraits<AstarPath.AstarDistribution>.Check = CheckType;
		StackTraits<AstarPath.AstarDistribution>.Push = Push;
	}

	static void Push(IntPtr L, AstarPath.AstarDistribution arg)
	{
		ToLua.Push(L, arg);
	}

	static bool CheckType(IntPtr L, int pos)
	{
		return TypeChecker.CheckEnumType(typeof(AstarPath.AstarDistribution), L, pos);
	}
}

