//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class DCETRuntime_IStaticMethodWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(DCETRuntime.IStaticMethod), typeof(System.Object));
		L.RegFunction("Run", Run);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Run(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 1)
			{
				DCETRuntime.IStaticMethod obj = (DCETRuntime.IStaticMethod)ToLua.CheckObject<DCETRuntime.IStaticMethod>(L, 1);
				obj.Run();
				return 0;
			}
			else if (count == 2)
			{
				DCETRuntime.IStaticMethod obj = (DCETRuntime.IStaticMethod)ToLua.CheckObject<DCETRuntime.IStaticMethod>(L, 1);
				object arg0 = ToLua.ToVarObject(L, 2);
				obj.Run(arg0);
				return 0;
			}
			else if (count == 3)
			{
				DCETRuntime.IStaticMethod obj = (DCETRuntime.IStaticMethod)ToLua.CheckObject<DCETRuntime.IStaticMethod>(L, 1);
				object arg0 = ToLua.ToVarObject(L, 2);
				object arg1 = ToLua.ToVarObject(L, 3);
				obj.Run(arg0, arg1);
				return 0;
			}
			else if (count == 4)
			{
				DCETRuntime.IStaticMethod obj = (DCETRuntime.IStaticMethod)ToLua.CheckObject<DCETRuntime.IStaticMethod>(L, 1);
				object arg0 = ToLua.ToVarObject(L, 2);
				object arg1 = ToLua.ToVarObject(L, 3);
				object arg2 = ToLua.ToVarObject(L, 4);
				obj.Run(arg0, arg1, arg2);
				return 0;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: DCETRuntime.IStaticMethod.Run");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

