//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class DCET_Runtime_ByteHelperWrap
{
	public static void Register(LuaState L)
	{
		L.BeginStaticLibs("ByteHelper");
		L.RegFunction("ToHex", ToHex);
		L.EndStaticLibs();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ToHex(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			byte[] arg0 = ToLua.CheckByteBuffer(L, 1);
			string arg1 = ToLua.CheckString(L, 2);
			string o = DCET.Runtime.ByteHelper.ToHex(arg0, arg1);
			LuaDLL.lua_pushstring(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

