//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class DCETRuntime_ErrorCodeWrap
{
	public static void Register(LuaState L)
	{
		L.BeginStaticLibs("ErrorCode");
		L.RegConstant("ERR_PeerDisconnect", 102008);
		L.RegConstant("ERR_SocketError", 102010);
		L.EndStaticLibs();
	}
}

