//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class FairyGUI_EMRenderTargetWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(FairyGUI.EMRenderTarget), null);
		L.RegFunction("EM_BeforeUpdate", EM_BeforeUpdate);
		L.RegFunction("EM_Update", EM_Update);
		L.RegFunction("EM_Reload", EM_Reload);
		L.RegVar("EM_sortingOrder", get_EM_sortingOrder, null);
		L.RegFunction("getEM_sortingOrder", get_EM_sortingOrder);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int EM_BeforeUpdate(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			FairyGUI.EMRenderTarget obj = (FairyGUI.EMRenderTarget)ToLua.CheckObject<FairyGUI.EMRenderTarget>(L, 1);
			obj.EM_BeforeUpdate();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int EM_Update(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			FairyGUI.EMRenderTarget obj = (FairyGUI.EMRenderTarget)ToLua.CheckObject<FairyGUI.EMRenderTarget>(L, 1);
			FairyGUI.UpdateContext arg0 = (FairyGUI.UpdateContext)ToLua.CheckObject<FairyGUI.UpdateContext>(L, 2);
			obj.EM_Update(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int EM_Reload(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			FairyGUI.EMRenderTarget obj = (FairyGUI.EMRenderTarget)ToLua.CheckObject<FairyGUI.EMRenderTarget>(L, 1);
			obj.EM_Reload();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_EM_sortingOrder(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			FairyGUI.EMRenderTarget obj = (FairyGUI.EMRenderTarget)o;
			int ret = obj.EM_sortingOrder;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index EM_sortingOrder on a nil value");
		}
	}
}

