//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class FairyGUI_BlendModeUtils_BlendFactorWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(FairyGUI.BlendModeUtils.BlendFactor), typeof(System.Object));
		L.RegFunction("New", _CreateFairyGUI_BlendModeUtils_BlendFactor);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("srcFactor", get_srcFactor, set_srcFactor);
		L.RegVar("dstFactor", get_dstFactor, set_dstFactor);
		L.RegVar("pma", get_pma, set_pma);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateFairyGUI_BlendModeUtils_BlendFactor(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 2)
			{
				UnityEngine.Rendering.BlendMode arg0 = (UnityEngine.Rendering.BlendMode)LuaDLL.luaL_checknumber(L, 1);
				UnityEngine.Rendering.BlendMode arg1 = (UnityEngine.Rendering.BlendMode)LuaDLL.luaL_checknumber(L, 2);
				FairyGUI.BlendModeUtils.BlendFactor obj = new FairyGUI.BlendModeUtils.BlendFactor(arg0, arg1);
				ToLua.PushObject(L, obj);
				return 1;
			}
			else if (count == 3)
			{
				UnityEngine.Rendering.BlendMode arg0 = (UnityEngine.Rendering.BlendMode)LuaDLL.luaL_checknumber(L, 1);
				UnityEngine.Rendering.BlendMode arg1 = (UnityEngine.Rendering.BlendMode)LuaDLL.luaL_checknumber(L, 2);
				bool arg2 = LuaDLL.luaL_checkboolean(L, 3);
				FairyGUI.BlendModeUtils.BlendFactor obj = new FairyGUI.BlendModeUtils.BlendFactor(arg0, arg1, arg2);
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: FairyGUI.BlendModeUtils.BlendFactor.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_srcFactor(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			FairyGUI.BlendModeUtils.BlendFactor obj = (FairyGUI.BlendModeUtils.BlendFactor)o;
			UnityEngine.Rendering.BlendMode ret = obj.srcFactor;
			LuaDLL.lua_pushinteger(L, (int)ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index srcFactor on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_dstFactor(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			FairyGUI.BlendModeUtils.BlendFactor obj = (FairyGUI.BlendModeUtils.BlendFactor)o;
			UnityEngine.Rendering.BlendMode ret = obj.dstFactor;
			LuaDLL.lua_pushinteger(L, (int)ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index dstFactor on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_pma(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			FairyGUI.BlendModeUtils.BlendFactor obj = (FairyGUI.BlendModeUtils.BlendFactor)o;
			bool ret = obj.pma;
			LuaDLL.lua_pushboolean(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index pma on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_srcFactor(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			FairyGUI.BlendModeUtils.BlendFactor obj = (FairyGUI.BlendModeUtils.BlendFactor)o;
			UnityEngine.Rendering.BlendMode arg0 = (UnityEngine.Rendering.BlendMode)LuaDLL.luaL_checknumber(L, 2);
			obj.srcFactor = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index srcFactor on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_dstFactor(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			FairyGUI.BlendModeUtils.BlendFactor obj = (FairyGUI.BlendModeUtils.BlendFactor)o;
			UnityEngine.Rendering.BlendMode arg0 = (UnityEngine.Rendering.BlendMode)LuaDLL.luaL_checknumber(L, 2);
			obj.dstFactor = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index dstFactor on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_pma(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			FairyGUI.BlendModeUtils.BlendFactor obj = (FairyGUI.BlendModeUtils.BlendFactor)o;
			bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
			obj.pma = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index pma on a nil value");
		}
	}
}

