//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class FairyGUI_RTLSupport_DirectionTypeWrap
{
	public static void Register(LuaState L)
	{
		L.BeginEnum(typeof(FairyGUI.RTLSupport.DirectionType));
		L.RegConstant("UNKNOW", FairyGUI.RTLSupport.DirectionType.UNKNOW);
		L.RegConstant("LTR", FairyGUI.RTLSupport.DirectionType.LTR);
		L.RegConstant("RTL", FairyGUI.RTLSupport.DirectionType.RTL);
		L.RegConstant("NEUTRAL", FairyGUI.RTLSupport.DirectionType.NEUTRAL);
		L.EndEnum();
		TypeTraits<FairyGUI.RTLSupport.DirectionType>.Check = CheckType;
		StackTraits<FairyGUI.RTLSupport.DirectionType>.Push = Push;
	}

	static void Push(IntPtr L, FairyGUI.RTLSupport.DirectionType arg)
	{
		ToLua.Push(L, arg);
	}

	static bool CheckType(IntPtr L, int pos)
	{
		return TypeChecker.CheckEnumType(typeof(FairyGUI.RTLSupport.DirectionType), L, pos);
	}
}

