//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class Pathfinding_GraphModifier_EventTypeWrap
{
	public static void Register(LuaState L)
	{
		L.BeginEnum(typeof(Pathfinding.GraphModifier.EventType));
		L.RegConstant("PostScan", Pathfinding.GraphModifier.EventType.PostScan);
		L.RegConstant("PreScan", Pathfinding.GraphModifier.EventType.PreScan);
		L.RegConstant("LatePostScan", Pathfinding.GraphModifier.EventType.LatePostScan);
		L.RegConstant("PreUpdate", Pathfinding.GraphModifier.EventType.PreUpdate);
		L.RegConstant("PostUpdate", Pathfinding.GraphModifier.EventType.PostUpdate);
		L.RegConstant("PostCacheLoad", Pathfinding.GraphModifier.EventType.PostCacheLoad);
		L.EndEnum();
		TypeTraits<Pathfinding.GraphModifier.EventType>.Check = CheckType;
		StackTraits<Pathfinding.GraphModifier.EventType>.Push = Push;
	}

	static void Push(IntPtr L, Pathfinding.GraphModifier.EventType arg)
	{
		ToLua.Push(L, arg);
	}

	static bool CheckType(IntPtr L, int pos)
	{
		return TypeChecker.CheckEnumType(typeof(Pathfinding.GraphModifier.EventType), L, pos);
	}
}

