//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class PF_SideWrap
{
	public static void Register(LuaState L)
	{
		L.BeginEnum(typeof(PF.Side));
		L.RegConstant("Colinear", PF.Side.Colinear);
		L.RegConstant("Left", PF.Side.Left);
		L.RegConstant("Right", PF.Side.Right);
		L.EndEnum();
		TypeTraits<PF.Side>.Check = CheckType;
		StackTraits<PF.Side>.Push = Push;
	}

	static void Push(IntPtr L, PF.Side arg)
	{
		ToLua.Push(L, arg);
	}

	static bool CheckType(IntPtr L, int pos)
	{
		return TypeChecker.CheckEnumType(typeof(PF.Side), L, pos);
	}
}

