-- Generated by CSharp.lua Compiler
local System = System
local DCETHotfix = DCET.Hotfix
System.namespace("DCET.Hotfix", function (namespace)
  namespace.class("AMHandler_1", function (namespace)
    return function (Message)
      local Handle, GetMessageType
      Handle = function (this, session, msg)
        return System.async(function (async, this, session, msg)
          local message = System.as(msg, Message)
          if message == nil then
            DCETHotfix.Log.Error("消息类型转换错误: " .. msg:GetType():getName() .. " to " .. System.typeof(Message):getName())
          end

          System.try(function ()
            async:Await(Run(this, session, message))
          end, function (default)
            local e = default
            DCETHotfix.Log.Error(e)
          end)
        end, nil, this, session, msg)
      end
      GetMessageType = function (this)
        return System.typeof(Message)
      end
      return {
        __inherits__ = function (out)
          return {
            out.DCET.Hotfix.IMHandler
          }
        end,
        Handle = Handle,
        GetMessageType = GetMessageType
      }
    end
  end)
end)
