-- Generated by CSharp.lua Compiler
local System = System
System.namespace("DCET.Hotfix", function (namespace)
  namespace.class("HotfixMessageDispatcher", function (namespace)
    return {}
  end)
end)
